# Setup
title : Argus-PAG
tagline: 'Start from REAL problems, create solutions that LAST'
title_separator          : "-"
description: 'We conduct research to apply static analysis on Dalvik bytecode of both Android applications and libraries, for the purpose of identifying potential malicious behaviors or program vulnerabilities.'

highlighter: rouge

# About/contact
author :
  name : Fengguo (Hugo) Wei
  email : fgwei521@gmail.com
  github : fgwei
  url: http://fgwei.arguslab.org

# Custom vars
version:             1.0.1

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://pag.arguslab.org

gems: ["jekyll-sitemap"]

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-85966762-1"

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
